return {
    {
        "mason-org/mason.nvim",
        build = ":MasonUpdate",
        opts = {
            registries = {
                "github:mason-org/mason-registry",
                "github:Crashdummyy/mason-registry",
            },
        },
    },
    {
        "WhoIsSethDaniel/mason-tool-installer.nvim",
        opts = {
            ensure_installed = {
                "stylua",
                "shellcheck",
                "shfmt",
                "flake8",
                "bash-language-server",
                "css-lsp",
                "docker-compose-language-service",
                "dockerfile-language-server",
                "eslint-lsp",
                "gofumpt",
                "goimports",
                "gopls",
                "html-lsp",
                "intelephense",
                "json-lsp",
                "lua-language-server",
                "marksman",
                "ols",
                "pint",
                "prettierd",
                "protols",
                "roslyn",
                "stylua",
                "tailwindcss-language-server",
                "vtsls",
                "vue-language-server",
                "yaml-language-server",
            },
            auto_update = false,
            run_on_start = true,
            start_delay = 2000, -- ms, avoids slowing startup
            debounce_hours = 12,
        },
    },
}
